version: 0.2

phases:
  install:
    runtime-versions:
      terraform: 1.4.6
  pre_build:
    commands:
      - terraform init
      - terraform validate
  
  build:
    commands:
      - terraform plan